### ISSUE TITLE
Error running building image using dockerfile

### ISSUE THREAD

**Issue by techmonte** [khaledhassan/simplescalar-docker#1]
Hi @khaledhassan, I'm interested in running SimpleScalar in a docker container and was referred to your repo.  When attempting to do a docker build using your DockerFile, I get the following error

`executor failed running [/bin/sh -c /simplescalar/build.bash]: exit code: 127`

I'm running Docker on MacOS (Catalina 10.15.7).  Is there something I'm missing in order to get the container image to build successfully?

**Comment by khaledhassan** [comment]
Hi @techmonte!

I'm very curious as to what you are doing with SimpleScalar and who referred you to my repo. 

I never really expected anyone to use this repository, though given the sparse and out of date instructions available online, I figured a Dockerfile (and bash script) was a decently reproduceable (and clean: both as in simple, and a single `docker rmi <blah>` to blow it all away) way of building SimpleScalar.

Apparently you and a few others (a watcher, 2 stars, and 3 forks) must have felt similarly, which is neat!

In my case, I needed this repo to work on a class project (which I've privately forked from this repo). The idea was that my partner and I would get SimpleScalar up and running with no modifications in this repo, and do our project-specific modifications in the other repo so that nobody else would see our work, merging any updates from this repo if the compilation didn't work due to a flaw in the script, etc.

----

To your question, I've just tried a `docker build .` on Alpine Linux, running Docker 19.03.12 and it built successfully. 

I tried digging into my old class notes to see if I could remember how to run the mibench benchmarks or otherwise know that SimpleScalar was indeed built properly, but I couldn't find anything useful on a quick search since it was so long ago.

Could you paste as much of your build log as possible, as a gist? Ideally after deleting whatever image was built, if any, so that it goes through the whole process of installing packages, etc. I would have attached my full build log but I forgot to increase the scrollback on my terminal...

I'm sure you've seen StackOverflow posts like
https://stackoverflow.com/questions/27820268/trying-to-run-docker-resulted-in-exit-code-127
and
https://stackoverflow.com/questions/31876031/the-command-bin-sh-c-returned-a-non-zero-code-127

With the variety of different solutions, more information is probably needed to figure out if any of them apply.

**Comment by techmonte** [comment]
Hi @khaledhassan ,

I had a class project as well (grad CS program) were we were required to leverage SimpleScalar. 🙂 I was referred to your repo by a classmate (likely the watcher). I was able to figure out my issue.  Had to make some modifications to the bash script but was able to get it running successfully.  Wound up getting a 100% for the assignment.  Early in the process, I was attempting to get everything set up on a Windows machine (bad move and burned two days 😑).  It was a pain.  Moved to Docker and once I got the bash script fixed, I was off to the races.  Thanks for your reply.

**Comment by khaledhassan** [comment]
Thanks for following up!

I'm really glad this repo has been useful to a handful of people, especially fellow grad students. 

In my class, the professor and TAs took the approach of "you all should be able to figure out how to install this, we aren't going to provide any instructions". There were lots of folks trying to dual boot their laptops (and some really screwing up their machines as a result), and others working out of VMs, which isn't too bad but sometimes a bit cumbersome.

The Dockerfile approach was really convenient to get setup, and saved our project when the motherboard on my laptop died halfway through the semester. Rather than struggle through some old setup instructions once more, I was back up and running after some apt-gets and git pulls.

When it came time to collect the results for our final report, I was also able to farm out the processing using a service called https://hyper.sh (now discontinued) which provided a cloud service that you could run containers on with the same kind of interface that "docker run" provides. We used GNU parallel to launch something like 30 jobs at once across Xeon class CPUs compared to my 4 core laptop. Lots of fun!

Thanks for sharing your experience, and good luck with the rest of your degree program!
